name: Feature Request
description: Suggest an idea for TinyMCE Field
labels:
  - enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see added to or changed in TinyMCE Field, and why?
    validations:
      required: true
